apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-hello-app.fullname" . }}
  labels:
    {{ include "go-hello-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "go-hello-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "go-hello-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: go-hello-app
          image: "{{ .Values.image }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: SECRET_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: secret-message
