apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-hello-app.fullname" . }}
  labels:
    {{ include "go-hello-app.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort | default 30080 }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "go-hello-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
